import "~/styles/globals.css";
import "~/styles/chat.css";

import { type Metadata } from "next";
import { Jersey_10 } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const jersey = Jersey_10({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-jersey",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${jersey.variable}`}>
      <body>{children}</body>
    </html>
  );
}
